### ISSUE TITLE
setup_annotation_dbs.py error

### ISSUE THREAD

**Issue by HirokiK0** [Kalan-Lab/lsaBGC#26]
Nice to meet you!
I would like to use this software, but the following error is preventing me from using it. Please let me know the solution.

> setup_annotation_dbs.py
Error: Provided directory for downloading annotation files does not exist!
Error: issues with downloading or seting up annotation database files! Please post to Github issues if unable to figure out!

**Comment by raufs** [comment]
Hi @HirokiK0, sorry for not seeing this issue earlier! 

Can you please provide more details around your installation process and computing system. Within the lsaBGC Git repo, do you see a subdirectory named `db/`?

**Comment by raufs** [comment]
Hi @HirokiK0 , thank you so much for opening this issue. It looks like NCBI reverted back the name of the folder when extracting the HMM profiles from their database. Will make the script for downloading databases more robust and update sometime today and comment back here once the update has been made.

**Comment by raufs** [comment]
This issue should now be resolved in v1.40 and downloading PGAP HMMs should be stable for any additional changes to the naming structure in the future. Please re-clone the github repo and try installation again. Thank you once more for reporting the issue.
